[workspace]
members = [
    "yummy",
    "yummy-core",
    "yummy-delta",
    "yummy-delta-py",
    "yummy-features",
    "yummy-features-py",
    "yummy-mlflow",
    "yummy-mlflow-py",
]

[workspace.package]
version = "0.0.8"
